- name: Apply Security Group Role
  hosts: localhost
  gather_facts: false
  # Create 2 security groups for HTTP Load Balancer access
  tasks: 
    - name: Set AWS default varaibles
      set_fact:
        aws_region: ap-southeast-2
    - name: Create VPC "pik-vpc"
      include_role: 
        name: create_pikachu_vpc
      vars:
        # VPC Name
        vpc_name: "pik-vpc"
        # Internet Gateway Name
        igw_name: "pik-vpc"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        # Values could be 
        # 10.0.0.0/16
        # 10.0.0.0/24
        cidr_block: "10.0.0.0/16" 
        # Subnet AZ
        subnet_1_cidr_block: "10.0.0.0/20"
        subnet_2_cidr_block: "10.0.16.0/20"
        subnet_3_cidr_block: "10.0.32.0/20"
        route_table_name: "pik-rtb-public"
        # Route destination CIDR to global internet
        destination_cidr_block: "0.0.0.0/0"
    - name: Create EC2 Security Group "pik-ec2-sg"
      amazon.aws.ec2_group:
        name: "pik-ec2-sg"
        description: "Security group for EC2 servers"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ pik_vpc_net_result.vpc.id }}"
        rules:
          # Allow global SSH
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            group_desc: Allow global SSH access        
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
            group_desc: Allow all traffic outbound
        state: present
      register: ec2_sg_result
      tags: create_sg
    - name: Display EC2 SG details
      debug:
        msg: "EC2 Security Group ID: {{ ec2_sg_result.group_id }}"
    - name: Create ELB Security Group "pik-elb-sg"
      ec2_group:
        name: "pik-elb-sg"
        description: "Security group for ELB"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "ap-southeast-2"
        vpc_id: "{{ pik_vpc_net_result.vpc.id }}"
        rules:
          # Global HTTP ingress 
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            group_desc: Global HTTP traffic inbound
          # Global HTTP ingress
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
            group_desc: Global HTTPS traffic inbound
        rules_egress:
          # ELB access EC2 on port 3000
          - proto: tcp
            from_port: 3000
            to_port: 3000
            group_id: "{{ ec2_sg_result.group_id }}"
            group_desc: ELB access EC2 API egress
      register: elb_sg_result
    - name: Display ELB SG details
      debug:
        msg: "ELB Security Group ID: {{ elb_sg_result.group_id }}"    
    - name: Create EC2 Key Pair
      ec2_key:
        name: pik-keypair
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"    
        force: false
    - name: Create EC2 
      # Fails because 
      amazon.aws.ec2_instance:
        # Ensure EC2 instance is created running 
        state: running 
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        # Instance name - auto generated 
        name: "pik-build-{{ now() }}"
        # User Data Script 
        user_data: |
          #!/bin/bash
          echo test message > /etc/quinn-wuz-here
          python -v 
        # SSH Key Pair Name 
        key_name: "pik-keypair"
        # Subnet 1 
        vpc_subnet_id: "{{ pik_subnet_1_result.subnet.id }}"
        # Instance size
        instance_type: t2.micro
        security_group: "{{ ec2_sg_result.group_id }}"
        network_interfaces:
          - assign_public_ip: true
        # Ubuntu Server 24.04 LTS (HVM), SSD Volume Type
        image_id: ami-003f5a76758516d1e 
        tags:
          Created: "{{ now() }}"
          Service: Pikachu 
          Environment: Testing
          Owner: Ash Ketchum
          Automation: Ansible
          Source: https://github.com/wrong-commit/ansible-aws-deployment


