- name: Apply Security Group Role
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_security_group
      vars:
        security_group_name: "web-server-sg"
        security_group_description: "Security group for web servers"
        security_group_rules:
          # Allow HTTP 
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          # Allow HTTPS
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          # Allow Global SSL         
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        security_group_egress_rules:
          - proto: all
            cidr_ip: 0.0.0.0/0