# This is a basic workflow to help you get started with Actions
name: CI_Build_EC2_AMI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master", "dev" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build EC2 AMI
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Install latest version of Ansible
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
      # Run Ansible playbook to build Security Group
      - name: Run Ansible Playbook / Build EC2 
        # Run Ansible from playbooks directory to assist with routing
        working-directory: ./playbooks
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook main_create_security_group.yml
      # Run Ansible playbook to build EC2 instance
      #- name: Run Ansible Playbook / Build EC2 
      #  env:
      #    ANSIBLE_HOST_KEY_CHECKING: False
      #  run: |
      #    ansible-playbook -i inventory/hosts.ini playbooks/main_launch_ec2.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }}
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
